safe: true
markdown: kramdown
pygments: true
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Varya Stepanova
    url:  http://varya.me/
    company:
        name: TMG Online
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
